language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  matrix:
    - WTFORMS=1.0.4
    - WTFORMS=1.0.5
    - WTFORMS=2.0
    - WTFORMS=2.1

install:
  - pip install WTForms==$WTFORMS
  - pip install -e ".[test]"

script:
  - isort --recursive --diff wtforms_alchemy tests && isort --recursive --check-only wtforms_alchemy tests
  - flake8 wtforms_alchemy tests
  - py.test tests
