language: python
sudo: required
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  matrix:
    - WTFORMS=2.2
    - WTFORMS=2.3
    - WTFORMS=3.0
    - SQLALCHEMY=1.4 WTFORMS=3.0

jobs:
  exclude:
    - python: 3.5
      env: WTFORMS=3.0
    - python: 3.5
      env: SQLALCHEMY=1.4 WTFORMS=3.0

install:
  - pip install WTForms==$WTFORMS
  - pip install -e ".[test]"
  - pip install https://github.com/jpic/wtforms-components/archive/wtforms3.zip
  - test -z $SQLALCHEMY || pip install SQLAlchemy==$SQLALCHEMY

script:
  - isort --recursive --diff wtforms_alchemy tests && isort --recursive --check-only wtforms_alchemy tests
  - flake8 wtforms_alchemy tests
  - py.test tests
